### ISSUE TITLE
Ghost clicking on macOS Ventura

### ISSUE THREAD

**Issue by joshdee** [daunroda/daunroda-app#2]
https://user-images.githubusercontent.com/35825246/193103771-be4f4a0c-36b6-4a6a-937e-b8fffcd327d7.mov
yeah it just does that for some reason

macOS Ventura 13.0 Beta (22A5352e), MacBook Pro M1

**Comment by joshdee** [comment]
<img width="1392" alt="Screenshot 2022-09-29 at 10 44 44 AM" src="https://user-images.githubusercontent.com/35825246/193104655-53a9c9c9-a00e-4389-a339-eb1d4f0818fd.png">

**Comment by joshdee** [comment]
nvm my stupid ass has a blank playlist icon, deleted

**Comment by alexthemaster** [comment]
Fixed in 3e4258c15f0d7ce30140ea5b792c14449f995bbb
